name: Checks

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest  # Updated to use the latest Ubuntu version

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test
        run: |
          docker-compose run --rm app sh -c "python manage.py wait_for_db"
          docker-compose run --rm app sh -c "python manage.py test"
          docker-compose run --rm app sh -c "flake8"
